### ISSUE TITLE
Can't link fb account with existing forum account

### ISSUE THREAD

**Issue by Swordancer** [Shade-/MyFacebook-Connect#66]
In first place you need to add yourforum.com/usercp.php?action=myfbconnect_link and yourforum.com/usercp.php?action=do_myfbconnect_link to Valid OAuth Redirect URIs and there is no such information in tutorial of installing.

Second, when im trying to link my account it redirects me to "wrong site" page with "usercp" writen in the searchbar (latest mybb version (1.8.17)).

**Comment by Swordancer** [comment]
https://odjechani.com.pl/

**Comment by Shade-** [comment]
That's an error page (you probably have Google SEO, that's why you see a "you may also try" page). Can't tell much as probably the language files are not synchronized with the latest release, but the only error I can think about regarding to UCP linking is related to the FB app not being configured properly.

Check the bug reports in the ACP; please open a new support thread in MyBBoost, given GitHub is to report bugs and this looks like an issue with your configuration.
